# Use an official Python runtime as a parent image
FROM python:3.6.7

# Set the working directory to /ml
WORKDIR /ml

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install libraries
RUN pip install h5py==2.10.0 

RUN pip install protobuf==3.6.1

RUN pip install tensorflow==1.15.0

RUN pip install pandas==0.25.3

RUN pip install seaborn==0.9.0

RUN pip install keras==2.3.1

RUN pip install matplotlib==3.1.2

RUN pip install scikit-learn

RUN pip install opencv-python

RUN pip install imageio==2.6.1

RUN pip install nibabel==2.5.0

RUN pip install Flask

RUN pip install jsonpickle

RUN pip install requests

RUN pip install PyPDF2

# Copy the current directory contents into the container at /ml
COPY . /ml

# Set the environment variable
ENV FLASK_APP test.py

# Expose port 5000
EXPOSE 5000

ENV CONFIG_PATH="app/config/config.json"

# Run the command to start Flask
CMD ["flask", "run", "--host=0.0.0.0"]
